# Generated by Django 5.2 on 2025-05-27 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aportaciones',
            field=models.TextField(default='texto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(default='2003-09-07'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='intereses',
            field=models.TextField(default='texto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(default='911', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ubicacion',
            field=models.CharField(default='por ahi', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trueque',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria'),
        ),
        migrations.AlterField(
            model_name='trueque',
            name='ubicacion',
            field=models.CharField(max_length=80),
        ),
    ]
