# Generated by Django 5.2 on 2025-05-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_aportaciones_customuser_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='aportaciones',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='intereses',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ubicacion',
        ),
    ]
