# Generated by Django 5.2.1 on 2025-06-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_aportaciones_customuser_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aportaciones',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(default='1990-01-01'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='imagen_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='intereses',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(default='00000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ubicacion',
            field=models.CharField(default='N/A', max_length=80),
        ),
    ]
