# Generated by Django 5.2.1 on 2025-06-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_rol_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueque',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=10),
        ),
    ]
