# Generated by Django 5.2.1 on 2025-06-19 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_trueque_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='publicidades',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicidades',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
