# Generated by Django 5.2.1 on 2025-06-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_servicio_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='precio_servicio',
            new_name='precio_producto',
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio_publicidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
