# Generated by Django 5.2.1 on 2025-06-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_precio_servicio_servicio_precio_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='dias_anuncio',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio_publicidad',
            field=models.DecimalField(decimal_places=2, default=250, editable=False, max_digits=10),
        ),
    ]
