# Generated by Django 5.2.1 on 2025-06-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_servicio_dias_anuncio_servicio_monto_pagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicidades',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='publicidades',
            name='fecha_inicio',
            field=models.DateTimeField(editable=False),
        ),
    ]
