# Generated by Django 5.2.1 on 2025-06-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_publicidades_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicidades',
            name='precio_publicidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
