# Generated by Django 5.2 on 2025-06-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_publicidades_precio_publicidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
    ]
